<a href="https://colab.research.google.com/github/OmarFloresPTY/my-google-colabs/blob/master/numpy_pandas_manipulacion_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulación y Transformación de Datos con Pandas y Numpy 📓🧮🐍

## 1. Uso de la librería Numpy

In [18]:
import numpy as np

### 1.1 Aprendiendo sobre los arrays y matrices {bidi,tridi}.mensionales

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]
#arr[1]
#arr[8]
#arr[9]

1

In [ ]:
len(arr)

9

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz[0][2]

3

In [ ]:
#arr[0:4]
arr[::3]

array([1, 4, 7])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
matriz_tridimensional = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [ ]:
matriz_tridimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
#matriz_tridimensional[0]
matriz_tridimensional[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz_tridimensional[2][2][2]

27

In [ ]:
matriz_tridimensional[1:,:,0:2]

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])

### 1.2 Tipos de datos en Numpy

#### Tipo de dato int32

In [ ]:
arr=np.array([0,1,2,3,4]) #método manual para crear un array del 0-4

In [ ]:
arr=np.arange(0,5) #método .arange(min,max-1) para crear un array del 0-4

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int32')

#### Tipo de dato float64

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr = np.array([1,2,3,4], dtype='float64') #método No.1 para castear un tipo de datos a otro tipo de datos numpy.

In [ ]:
arr.astype(np.float64) #método No.2 para castear un tipo de datos a otro tipo de datos en numpy.

array([1., 2., 3., 4.])

#### Tipo de dato boole64

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
arr=arr.astype(np.bool_)

In [ ]:
arr

array([False,  True,  True,  True,  True])

#### Tipo de dato string64

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
arr = arr.astype(np.string_)

In [ ]:
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [ ]:
arr = np.array(['0','1','2','3','4'])
#arr = np.array(['Hello','1','2','3','4']) #No puede convertir un texto a entero.

In [ ]:
arr = arr.astype(np.int8) #Investigar int8 y int32

Si quieres conocer todos los tipos de datos de numpy, visita su sitio web oficial: https://numpy.org/doc/stable/user/basics.types.html

### 1.3 Dimensiones

* Scalar = Un único valor por separado (unidad).
* Vector = Una colección unidemensional de elementos del mismo tipo de datos.
* Matrix = Una colección bidimensional de elementos del mismo tipo de datos. (Filas y Columnas)
* Tensor = Una colección de n-dimension de elementos del mismo tipo de datos.

<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMjQ0/MDAxNTkwMzcxNTgxMjgx.zVM_8O3aWx1DUjeKFx-FRXeHS1KVHWfdSiOBE2--1k4g.6z_U8ssbX1lwelBEqUxjtyutk2y6HSNTvk5a7pTYIWkg.PNG.nabilera1/image.png?type=w800">

In [ ]:
scalar = np.array(42)
print(scalar)

42


In [ ]:
scalar.ndim #Nos permite saber cuantas dimensiones tiene nuestro objeto numpy creado.

0

In [ ]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [ ]:
vector.ndim

1

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
matrix.ndim

2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
tensor.ndim

3

### 1.4 Creando arrays
Creando arrays con las diferentes funciones que tiene numpy, hasta el momento hemos creado esta estructura de datos pasando como parámetro una lista.

#### range(min,max)
* El método range(min,max)es un método creado por python pero no por numpy.

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### np.arange(min,max-1,pasos)
* El método np.arange(min,max-1,pasos) sí es un método creado por numpy para crear arrays desde un rango dado.

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### np.zeros(n) (vector)
* El método np.zeros(n) crea un array con la cantidad de ceros indicados en n.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

#### np.zeros((n,m)) (matriz)
* Crea una matriz de ceros con la sintaxis np.zeros((n,m)) ==> n y m son pasados como parámetros.

In [ ]:
#np.zeros((3,3))
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### np.ones((n,m))
* Crea una matriz de unos con la sintaxis np.ones((n,m)) ==> n y m son pasados como parámetros.

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### np.linspace(min,max,cant)
* Crea una distribución normalizada y ordenada de datos del 0 al 10 generados a partir de 100 datos.

In [ ]:
np.linspace(0,10,100) #Crea una distribución normalizada y ordenada de datos del 0 al 10 generados a partir de 100 datos.

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

#### np.eye(n)
* Genera una matriz identidad NxN donde N es el valor pasado como parámetro.

In [ ]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### np.random
* np.random.rand() genera un escalar del 0 al 1.
* np.random.rand(n) generara un array con n cantidad de elementos del 0 al 1.
* np.rand(n,m) genera una matriz de n,m cantidad de elementos del 0 al 1.
* np.randint(min,max) genera un número aleatorio entre el min y el max.
* np.randint(min,max,(n,m)) genera un matriz de n,m de elementos aleatorios entre el min y el max.


In [ ]:
np.random.rand()

0.6906089723726002

In [ ]:
np.random.rand(4)

array([0.96685689, 0.63863924, 0.42806768, 0.03635644])

In [ ]:
np.random.rand(4,4)

array([[0.02808761, 0.43323258, 0.50477401, 0.67823693],
       [0.52756445, 0.22223687, 0.14752001, 0.8626257 ],
       [0.05345123, 0.54952941, 0.33329937, 0.81996029],
       [0.37559612, 0.80355444, 0.33105405, 0.64180839]])

In [ ]:
np.random.randint(1,15)

14

In [ ]:
np.random.randint(1,100,(10,10))

array([[17, 14, 80, 33, 45, 75, 35, 61, 96, 99],
       [ 4, 49, 36, 31, 55, 77, 36, 71,  1, 24],
       [88, 75,  6, 12, 70, 22, 86,  8, 33, 50],
       [ 7, 45, 68, 94, 83, 46, 83, 45, 18, 85],
       [39, 29, 55, 96,  5, 37, 61, 77, 54,  3],
       [77,  3, 67, 46,  5, 45, 65, 76, 79, 60],
       [31, 67,  1, 85, 13,  9,  1, 80, 59,  4],
       [88, 98, 74, 66,  8, 85, 37, 65, 68, 17],
       [49, 83, 84, 38, 42, 24, 77,  6, 35, 37],
       [79, 39, 93, 67, 77, 44, 32, 63, 34, 25]])

### 1.5 Shape y Reshape
El método shape nos permite ver como está construido el objeto numpy, eso quiere decir que nos muestra las dimensiones y el reshape nos da la opción de ordenarlos de diferente forma siempre y cuando se respete la cantidad de elementos en el objeto numpy.

In [ ]:
arr = np.random.randint(1,10,(3,2))

In [ ]:
arr.shape

(3, 2)

In [ ]:
arr

array([[6, 8],
       [1, 7],
       [7, 1]])

In [ ]:
arr.reshape(1,6)
#arr.reshape(2,3)
#arr.reshape(6,1)

array([[6, 8, 1, 7, 7, 1]])

In [ ]:
np.reshape(arr,(1,6))

array([[6, 8, 1, 7, 7, 1]])

In [ ]:
np.reshape(arr,(2,3),'C')

array([[6, 8, 1],
       [7, 7, 1]])

In [ ]:
np.reshape(arr,(2,3),'F')

array([[6, 7, 7],
       [1, 8, 1]])

In [ ]:
np.reshape(arr,(2,3),'A')

array([[6, 8, 1],
       [7, 7, 1]])

### 1.6 Funciones Principales de Numpy

In [ ]:
arr = np.random.randint(1,20,10)

In [ ]:
arr

array([ 2,  1,  9,  5, 11, 14,  2,  6,  9, 17])

In [ ]:
matriz = arr.reshape(2,5)

In [ ]:
matriz

array([[ 2,  1,  9,  5, 11],
       [14,  2,  6,  9, 17]])

#### max()
max() nos trae el valor máximo de un array o de una matriz, este método se le puede pasar dos parámetro como lo son el 0 y el 1.
* max(0): Trae los valores máximos de cada columna. Devuelve un array.
* max(1): Trae los valores máximos de cada fila. Devuelve un array.

In [ ]:
arr.max()

17

In [ ]:
matriz.max()

17

In [ ]:
matriz.max(1) #Realiza la búsqueda del mayor por fila
#matriz.max(0) #Realiza la búsqueda del mayor por columna

array([14,  2,  9,  9, 17])

#### argmax()
argmax() a diferencia del max() este solo trae la posición del valor mayor dentro de la array o matriz, este método se le puede pasar dos paráremtros como lo son el 0 y el 1.
* argmax(0): Trae los indices de los valores máximos de cada columna. Devuelve un array.
* argmax(1): Trae los indices de los valores máximos de cada fila. Devuelve un array.

In [ ]:
matriz.argmax()

9

In [ ]:
matriz.argmax(0) #Por columna
#matriz.argmax(1) #Por fila

array([1, 1, 0, 1, 1])

#### min()
min() nos trae el valor mínimo de un array o de una matriz, este método se le puede pasar dos parámetro como lo son el 0 y el 1.
* min(0): Trae los valores mínimos de cada columna. Devuelve un array.
* min(1): Trae los valores mínimos de cada fila. Devuelve un array.

In [ ]:
arr.min()

1

In [ ]:
matriz.min()

1

In [ ]:
#matriz.min(0)
matriz.min(1)

array([1, 2])

#### argmin()
argmin() a diferencia del min() este solo trae la posición del valor menor dentro de la array o matriz, este método se le puede pasar dos paráremtros como lo son el 0 y el 1.
* argmin(0): Trae los indices de los valores mínimos de cada columna. Devuelve un array.
* argmax(1): Trae los indices de los valores mínimos de cada fila. Devuelve un array.

In [ ]:
matriz.argmin()

1

In [ ]:
matriz.argmin(0)
#matriz.argmin(1)

array([0, 0, 1, 0, 0])

#### ptp()
Calcula la diferencia entre el valor máximo y el mínimo de cada array o matriz. Al igual que los otros métodos podemos aplicarlo a las filas y a las columnas

In [ ]:
arr.ptp()

16

In [ ]:
matriz.ptp()

16

In [ ]:
matriz

array([[ 2,  1,  9,  5, 11],
       [14,  2,  6,  9, 17]])

In [ ]:
matriz.ptp(0)
#matriz.ptp(1)

array([12,  1,  3,  4,  6])

#### percentile()
Los percentiles son valores que dividen un conjunto de datos estadísticos, de forma que un porcentaje de los mismos quede por debajo de dicho valor.

In [ ]:
arr.sort() #sort() es un método que nos permite ordenar los elementos.
print(arr)
matriz.sort()
print(f'=====================\n{matriz}')

[ 1  2  2  5  6  9  9 11 14 17]
[[ 1  2  2  5  6]
 [ 9  9 11 14 17]]


In [ ]:
np.percentile(arr,50)

7.5

In [ ]:
np.percentile(matriz,50)

7.5

#### median()
Calcula la mediana de un conjunto de datos.
Al igual que todas la funciones que hemos visto hasta aquí nos permite realizar estas operaciones de forma general, por fila y columna

In [ ]:
np.median(arr)

In [ ]:
np.median(matriz,1)

array([ 2., 11.])

#### std()
Nos permite conocer la desviación estándar de un conjunto de datos.
Se puede calcular de forma general o por filas o por columnas.

In [ ]:
np.std(arr)

5.102940328869229

In [ ]:
np.std(matriz,0)

array([4. , 3.5, 4.5, 4.5, 5.5])

#### var()
Podemos tener la varianza en un conjunto de datos. Se puede calcular de forma general o por filas o por columnas.

In [ ]:
np.var(arr)

26.04

In [ ]:
np.var(matriz,0)

#### mean()
Calcula la media de un conjunto de datos. Se puede calcular de forma general o por filas o por columnas.

In [ ]:
np.mean(arr)

7.6

In [ ]:
np.mean(matriz)

7.6

In [ ]:
np.mean(matriz,0)

array([ 5. ,  5.5,  6.5,  9.5, 11.5])

#### concatener(array1,array2)
Nos permite concatenear arrays.

In [ ]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))

In [ ]:
a,b

(array([[7, 4],
        [2, 8]]),
 array([[8, 4],
        [5, 1]]))

In [ ]:
np.concatenate((a,b))

array([[7, 4],
       [2, 8],
       [8, 4],
       [5, 1]])

In [ ]:
np.concatenate((a,b),axis=1)

array([[7, 4, 8, 4],
       [2, 8, 5, 1]])

#### expand_dim()
Nos permite expandir la dimensión de un array.

In [ ]:
c = np.array([1,2])
c.ndim

1

In [ ]:
c = np.expand_dims(c,axis=0)
c

array([[1, 2]])

In [ ]:
c = np.expand_dims(c,axis=1)
c

array([[1],
       [2]])

In [ ]:
np.concatenate((a,c),axis=0)
#np.concatenate((a,c),axis=1) #Nos genera un error porque aunque sean de la misma dimensión, no son del mismo tamaño de la matriz.

array([[6, 3],
       [7, 7],
       [1, 2]])

#### T (Transpuesta de una matriz)

In [ ]:
d = np.random.randint(2,10,(2,3))
d

array([[9, 4, 6],
       [7, 7, 8]])

In [ ]:
d.T

array([[9, 7],
       [4, 7],
       [6, 8]])

### 1.7 Copy

A continuación veremos la mala práctica de copiar un conjunto de datos en numpy.

In [ ]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
trozo = arr[0:6]
trozo

array([0, 1, 2, 3, 4, 5])

In [ ]:
trozo[:] = 0
trozo

array([0, 0, 0, 0, 0, 0])

In [ ]:
arr

array([ 0,  0,  0,  0,  0,  0,  6,  7,  8,  9, 10])

La forma correcta de hacerlo es la siguiente

In [ ]:
arr_copy = arr.copy()

In [ ]:
arr_copy[:] = 100
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

### 1.8 Condiciones

In [ ]:
arr = np.linspace(1,10,10,dtype='int8')

In [ ]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10], dtype=int8)

In [ ]:
indices_cond = arr > 5

In [ ]:
indices_cond

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [ ]:
arr[indices_cond]
#arr[arr > 5] #Es exactamente lo mismo, es otra forma de evaluar la condición.

array([ 6,  7,  8,  9, 10], dtype=int8)

In [ ]:
arr[(arr > 5) & (arr<9)]

array([6, 7, 8], dtype=int8)

In [ ]:
arr[arr > 5] = 99
#arr

In [ ]:
arr[arr==99]

array([99, 99, 99, 99, 99], dtype=int8)

### 1.9 Operaciones

In [ ]:
lista = [1,2]

In [ ]:
lista * 2

[1, 2, 1, 2]

In [ ]:
arr=np.arange(0,10)

In [ ]:
arr2 = arr.copy()

In [ ]:
arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
matriz = arr.reshape(2,5)

In [ ]:
matriz

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
matriz2 = matriz.copy()

In [ ]:
matriz2

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

* Multiplicación

In [ ]:
arr * 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
arr * arr2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [ ]:
matriz * matriz2

array([[ 0,  1,  4,  9, 16],
       [25, 36, 49, 64, 81]])

* Suma

In [ ]:
arr + 2

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [ ]:
arr + arr2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [ ]:
matriz + matriz2

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18]])

* División

Lo interesante de este problema es que si existe un elemento que es cero, en lugar de saltar un error, numpy nos indica en que posición se proporcionó el error y sigue con las operaciones en cada elemento.

In [ ]:
1/arr

<ipython-input-54-016353831300>:1: RuntimeWarning: divide by zero encountered in true_divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [ ]:
arr / arr2

<ipython-input-55-5a1b3fd1a087>:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr2


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [ ]:
matriz / matriz2

* Potencia

In [ ]:
arr ** 2

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

* Producto Punto

In [ ]:
np.matmul(matriz,matriz2.T)

array([[ 30,  80],
       [ 80, 255]])

In [ ]:
matriz @ matriz2.T

array([[ 30,  80],
       [ 80, 255]])

## Uso de la libreria Pandas
Pandas es una librería de Python especializada en el manejo y análisis de estructuras de datos. El nombre viene de “Panel data”.
* Velocidad,Poco código, Múltiples formatos de archivos,Alineación inteligente
* Pandas Series: Es muy parecido a un array unidimensional de numpy, es indexado, puedo utilizar slices,puedo entrar a los objetos en específicos, optimizado y puede manejar diferentes tipos de datos.
* Pandas DataFrame: Es un objeto hecho de arrayz pero matricial (filas y columnas) cada fila tiene un índice. Optimiza mucho la memoria.

In [22]:
import pandas as pd

### 2.1 Pandas Series

In [ ]:
psg_player = pd.Series(['Navas','Mbappe','Neymar','Messi'], index=[1,7,10,30])
psg_player

1      Navas
7     Mbappe
10    Neymar
30     Messi
dtype: object

In [ ]:
psg_player[7]

'Mbappe'

In [ ]:
psg_player = pd.Series(['Navas','Mbappe','Neymar','Messi'])
psg_player

0     Navas
1    Mbappe
2    Neymar
3     Messi
dtype: object

In [ ]:
psg_player[2:]

2    Neymar
3     Messi
dtype: object

In [ ]:
dictionary = {1:'Navas',7:'Mbappe',10:'Neymar',30:'Messi'}
psg_player = pd.Series(dictionary)
psg_player

In [ ]:
psg_player[7]

'Mbappe'

### 2.2 Pandas DataFrame

In [ ]:
dictionary = {'Jugador':['Navas','Mbappe','Neymar','Messi'],
 'Altura':[183.0,170.0,170.0,165.0],
 'Goles':[2,200,200,200]}

In [ ]:
df_player = pd.DataFrame(dictionary,index=[1,7,10,30])
df_player

Jugador  Altura  Goles
1    Navas   183.0      2
7   Mbappe   170.0    200
10  Neymar   170.0    200
30   Messi   165.0    200

In [ ]:
df_player = pd.DataFrame(dictionary)
df_player

Jugador  Altura  Goles
0   Navas   183.0      2
1  Mbappe   170.0    200
2  Neymar   170.0    200
3   Messi   165.0    200

In [ ]:
df_player.columns

Index(['Jugador', 'Altura', 'Goles'], dtype='object')

In [ ]:
list(df_player)

['Jugador', 'Altura', 'Goles']

In [ ]:
df_player.index

Int64Index([1, 7, 10, 30], dtype='int64')

### 2.3 Leer archivos CSV y JSON con Pandas

In [24]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
!mkdir '/content/drive/MyDrive/Pandas'

In [25]:
df_books = pd.read_csv('/content/drive/MyDrive/Pandas/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv')

* El parámetro **sep** de la función read_csv permite cambiar las separaciones que vienen en el csv, por lo general los csv trabajan con comas (,) pero de no ser así podemos cambiar estos separadores.
* El parámetro **header** permite mover el encabezado del dataframe bajando por filas.
* El parámetro **names** nos permite cambiarles el nombre a las columnas, nos permite personalizar.



In [ ]:
df_books = pd.read_csv('/content/drive/MyDrive/Pandas/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep='|',header=1)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books = pd.read_csv('/content/drive/MyDrive/Pandas/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',sep=',',header=0,)

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.columns

Index(['Name', 'Author', 'User Rating', 'Reviews', 'Price', 'Year', 'Genre'], dtype='object')

In [ ]:
df_books = pd.read_csv('/content/drive/MyDrive/Pandas/bestsellers-with-categories_e591527f-ae45-4fa5-b0d1-d50142128fa6.csv',
                       sep=',',header=0,names=['Namesss', 'Authorrrr', 'User Ratinggg', 'Reviewsss', 'Priceee', 'Yearrr', 'Genreeee'])

In [ ]:
df_books

Namesss  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                    Authorrrr  User Ratinggg  Reviewsss  Priceee  Yearrr  \
0                    JJ Smith            4.7      17350        8    2016   
1                Stephen King            4.6       2052       22    2011   
2          Jordan B. Peterson            4.7      18979       15    2018   
3               George Orwell            4.7      21424        6    2017   
4    National Geographic Kids            4.8       7665       12    2019   
..                        ...            ...        ...      ...     ...   
545               Jeff Kinney            4.9       9413        8    2019   
546               Jen Sincero            4.7      14331        8    2016   
547               Jen Sincero            4.7      14331        8    2017   
548               Jen Sincero            4.7      14331        8    2018   
549               Jen Sincero            4.7      14331        8    2019   

        Genreeee  
0    Non Fiction  
1        Fiction  
2    Non Fiction  
3        Fiction  
4    Non Fiction  
..           ...  
545      Fiction  
546  Non Fiction  
547  Non Fiction  
548  Non Fiction  
549  Non Fiction  

[550 rows x 7 columns]

In [ ]:
pd.read_json('/content/drive/MyDrive/Pandas/hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json')

Name                                               Link  \
0              Mrs. Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
1            Hannah Abbott  https://www.hp-lexicon.org/character/abbott-fa...   
2            Abel Treetops  https://www.hp-lexicon.org/character/abel-tree...   
3         Euan Abercrombie  https://www.hp-lexicon.org/character/abercromb...   
4     Aberforth Dumbledore  https://www.hp-lexicon.org/character/dumbledor...   
...                    ...                                                ...   
1935        Georgi Zdravko  https://www.hp-lexicon.org/character/georgi-zd...   
1936                Zograf       https://www.hp-lexicon.org/character/zograf/   
1937                 Zonko        https://www.hp-lexicon.org/character/zonko/   
1938     Valentina Vázquez  https://www.hp-lexicon.org/character/valentina...   
1939         Zygmunt Budge  https://www.hp-lexicon.org/character/zygmunt-b...   

                                                  Descr  Gender Species/Race  \
0     Mrs. Abbott was the mother of Hannah Abbott, a...  Female        Witch   
1     Hannah Abbott is a Hufflepuff student in Harry...  Female        Witch   
2     Abel Treetops was a wizard from Cincinnati who...    Male       Wizard   
3     Euan Abercrombie was a small boy with prominen...    Male       Wizard   
4     Aberforth Dumbledore was a tall, thin, grumpy-...    Male       Wizard   
...                                                 ...     ...          ...   
1935  Georgi Zdravko played Keeper for the Bulgarian...    Male       Wizard   
1936  Zograf played Keeper for the Bulgarian Nationa...     NaN       Wizard   
1937  Founder(?) of Zonko’s Joke Shop. Possibly a re...     NaN      Unknown   
1938  Valentina Vázquez was President of the Argenti...  Female        Witch   
1939  Zygmunt Budge is considered to be one of the m...    Male       Wizard   

            Blood                 School  \
0     Muggle-born                Unknown   
1      Half-blood  Hogwarts - Hufflepuff   
2         Unknown                Unknown   
3         Unknown  Hogwarts - Gryffindor   
4      Half-blood     Hogwarts - Student   
...           ...                    ...   
1935      Unknown                Unknown   
1936      Unknown                Unknown   
1937      Unknown                Unknown   
1938      Unknown                Unknown   
1939      Unknown     Hogwarts - Student   

                                         Profession  
0                                           Unknown  
1                    Landlady of the Leaky Cauldron  
2                                           Unknown  
3                                           Unknown  
4                                            Barman  
...                                             ...  
1935                      Quidditch player (Seeker)  
1936                      Quidditch player (Keeper)  
1937                                        Unknown  
1938  President of the Argentinian Council of Magic  
1939    Potions Master, Potioneer, Inventor, Author  

[1940 rows x 8 columns]

Otra forma de leer el .JSON es utilizar la nomenclatura key:value cambiando el tipo con el parámetro typ='Series'

In [ ]:
read_json = pd.read_json('/content/drive/MyDrive/Pandas/hpcharactersdataraw_3d934e85-dfa4-42ec-8520-fadfbecae574.json',typ='Series')

In [ ]:
read_json

0       {'Name': 'Mrs. Abbott', 'Link': 'https://www.h...
1       {'Name': 'Hannah Abbott', 'Link': 'https://www...
2       {'Name': 'Abel Treetops', 'Link': 'https://www...
3       {'Name': 'Euan Abercrombie', 'Link': 'https://...
4       {'Name': 'Aberforth Dumbledore', 'Link': 'http...
                              ...                        
1935    {'Name': 'Georgi Zdravko', 'Link': 'https://ww...
1936    {'Name': 'Zograf', 'Link': 'https://www.hp-lex...
1937    {'Name': 'Zonko', 'Link': 'https://www.hp-lexi...
1938    {'Name': 'Valentina Vázquez', 'Link': 'https:/...
1939    {'Name': 'Zygmunt Budge', 'Link': 'https://www...
Length: 1940, dtype: object

In [ ]:
read_json[0]

{'Name': 'Mrs. Abbott',
 'Link': 'https://www.hp-lexicon.org/character/abbott-family/mrs-abbott/',
 'Descr': 'Mrs. Abbott was the mother of Hannah Abbott, a Hufflepuff in Harry’s year. Mrs. Abbott was found dead in the fall of 1996, having been murdered by Death Eaters (HBP11). ',
 'Gender': 'Female',
 'Species/Race': 'Witch',
 'Blood': 'Muggle-born',
 'School': 'Unknown',
 'Profession': 'Unknown'}

### 2.4 iloc y loc

In [ ]:
df_books[0:4]

Name              Author  User Rating  \
0            10-Day Green Smoothie Cleanse            JJ Smith          4.7   
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   
3                   1984 (Signet Classics)       George Orwell          4.7   

   Reviews  Price  Year        Genre  
0    17350      8  2016  Non Fiction  
1     2052     22  2011      Fiction  
2    18979     15  2018  Non Fiction  
3    21424      6  2017      Fiction

Filtrando por columnas de un dataFrame

In [ ]:
df_books['Name']

0                          10-Day Green Smoothie Cleanse
1                                      11/22/63: A Novel
2                12 Rules for Life: An Antidote to Chaos
3                                 1984 (Signet Classics)
4      5,000 Awesome Facts (About Everything!) (Natio...
                             ...                        
545         Wrecking Ball (Diary of a Wimpy Kid Book 14)
546    You Are a Badass: How to Stop Doubting Your Gr...
547    You Are a Badass: How to Stop Doubting Your Gr...
548    You Are a Badass: How to Stop Doubting Your Gr...
549    You Are a Badass: How to Stop Doubting Your Gr...
Name: Name, Length: 550, dtype: object

In [ ]:
#df_books[['Name','Author']]
df_books[['Name','Author','Year']]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  Year  
0                    JJ Smith  2016  
1                Stephen King  2011  
2          Jordan B. Peterson  2018  
3               George Orwell  2017  
4    National Geographic Kids  2019  
..                        ...   ...  
545               Jeff Kinney  2019  
546               Jen Sincero  2016  
547               Jen Sincero  2017  
548               Jen Sincero  2018  
549               Jen Sincero  2019  

[550 rows x 3 columns]

Filtrar por filas con PandasFrame utilizando loc.

In [ ]:
df_books.loc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.loc[0:4,['Name','Author']] #Es un slice mucho más complejo o personalizado que el primero que vimos en este apartado.

Name                    Author
0                      10-Day Green Smoothie Cleanse                  JJ Smith
1                                  11/22/63: A Novel              Stephen King
2            12 Rules for Life: An Antidote to Chaos        Jordan B. Peterson
3                             1984 (Signet Classics)             George Orwell
4  5,000 Awesome Facts (About Everything!) (Natio...  National Geographic Kids

Operaciones matematicas por columnas gracias a loc.

In [ ]:
df_books.loc[:,['Reviews']] * -1

Reviews
0     -17350
1      -2052
2     -18979
3     -21424
4      -7665
..       ...
545    -9413
546   -14331
547   -14331
548   -14331
549   -14331

[550 rows x 1 columns]

In [ ]:
df_books.loc[:,['Author']] == 'JJ Smith' #Nos dice quien de todas las filas tiene como nombre de autor JJ Smith

Author
0      True
1     False
2     False
3     False
4     False
..      ...
545   False
546   False
547   False
548   False
549   False

[550 rows x 1 columns]

Función iloc. Es similar al loc, solo que la palabra iloc la vocal i viene de index, esto quiere decir que vamos a filtrar todo por medio de indices nada más.

In [ ]:
df_books.iloc[:]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.iloc[:,0:3]

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  
0                    JJ Smith          4.7  
1                Stephen King          4.6  
2          Jordan B. Peterson          4.7  
3               George Orwell          4.7  
4    National Geographic Kids          4.8  
..                        ...          ...  
545               Jeff Kinney          4.9  
546               Jen Sincero          4.7  
547               Jen Sincero          4.7  
548               Jen Sincero          4.7  
549               Jen Sincero          4.7  

[550 rows x 3 columns]

In [ ]:
df_books.iloc[1,3] * -1

-2052

In [ ]:
df_books.iloc[:2,2:]

User Rating  Reviews  Price  Year        Genre
0          4.7    17350      8  2016  Non Fiction
1          4.6     2052     22  2011      Fiction

### 2.5 Agregar o eliminar datos de mi DataFrame

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

Eliminar las columnas de un dataFrame

axis=(1=Columnas,0=filas)

In [ ]:
df_books.drop('Genre',axis=1).head(2) #con drop solo eliminamos la salida, pero no del dataFrame

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [ ]:
df_books.drop('Genre',axis=1,inplace=True)#Ahora sí lo eliminamos del dataFrame

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year  
0  2016  
1  2011

In [ ]:
df_books = df_books.drop('Year',axis=1)#Ahora sí lo eliminamos del dataFrame

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8
1              11/22/63: A Novel  Stephen King          4.6     2052     22

In [ ]:
del df_books['Price'] #No es una buena práctica

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

Eliminar Filas de un DataFrame

In [ ]:
df_books.drop(0,axis=0).head(2) #Elimina la fila número cero del DataFrame (SOLO FORMATEA LA SALIDA)

Name              Author  User Rating  \
1                        11/22/63: A Novel        Stephen King          4.6   
2  12 Rules for Life: An Antidote to Chaos  Jordan B. Peterson          4.7   

   Reviews  
1     2052  
2    18979

In [ ]:
df_books.drop([0,1,2],axis=0).head(2) #Elimina la fila número cero,uno y dos del DataFrame (SOLO FORMATEA LA SALIDA)

Name  \
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  
3             George Orwell          4.7    21424  
4  National Geographic Kids          4.8     7665

In [ ]:
df_books.drop(range(0,10),axis=0).head(2) #Elimina las filas que se encuentren en un rango del DataFrame (SOLO FORMATEA LA SALIDA)

Name            Author  \
10                          A Man Called Ove: A Novel   Fredrik Backman   
11  A Patriot's History of the United States: From...  Larry Schweikart   

    User Rating  Reviews  
10          4.6    23848  
11          4.6      460

In [ ]:
df_books.drop(range(0,10),axis=0).head(2)

Agregar columnas en un dataFrame

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350
1              11/22/63: A Novel  Stephen King          4.6     2052

In [ ]:
df_books['Nueva_Columna'] = np.nan #nan es un valor no númerico, la columna agregada modifica todo el dataFrame real.

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350   
1              11/22/63: A Novel  Stephen King          4.6     2052   

   Nueva_Columna  
0            NaN  
1            NaN

In [ ]:
data=np.arange(0,df_books.shape[0])
data

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [ ]:
df_books['Rango'] = data

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva_Columna  Rango  
0                    JJ Smith          4.7    17350            NaN      0  
1                Stephen King          4.6     2052            NaN      1  
2          Jordan B. Peterson          4.7    18979            NaN      2  
3               George Orwell          4.7    21424            NaN      3  
4    National Geographic Kids          4.8     7665            NaN      4  
..                        ...          ...      ...            ...    ...  
545               Jeff Kinney          4.9     9413            NaN    545  
546               Jen Sincero          4.7    14331            NaN    546  
547               Jen Sincero          4.7    14331            NaN    547  
548               Jen Sincero          4.7    14331            NaN    548  
549               Jen Sincero          4.7    14331            NaN    549  

[550 rows x 6 columns]

Agregar filas en un dataFrame

In [ ]:
df_books.append(df_books)#Se puede agregar tuplas, listas y objetos.

<ipython-input-69-2d66bcf3bac0>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books.append(df_books)


Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Nueva_Columna  Rango  
0                    JJ Smith          4.7    17350            NaN      0  
1                Stephen King          4.6     2052            NaN      1  
2          Jordan B. Peterson          4.7    18979            NaN      2  
3               George Orwell          4.7    21424            NaN      3  
4    National Geographic Kids          4.8     7665            NaN      4  
..                        ...          ...      ...            ...    ...  
545               Jeff Kinney          4.9     9413            NaN    545  
546               Jen Sincero          4.7    14331            NaN    546  
547               Jen Sincero          4.7    14331            NaN    547  
548               Jen Sincero          4.7    14331            NaN    548  
549               Jen Sincero          4.7    14331            NaN    549  

[1100 rows x 6 columns]

###2.6 Manejo de datos nulos

In [ ]:
dict_example = {'col1':[1,2,3,np.nan],
 'col2':[3,np.nan,6,7],
 'col3':['a','b','c',None]}


In [ ]:
df = pd.DataFrame(dict_example)

In [ ]:
df

col1  col2  col3
0   1.0   3.0     a
1   2.0   NaN     b
2   3.0   6.0     c
3   NaN   7.0  None

In [ ]:
df.isnull()

col1   col2   col3
0  False  False  False
1  False   True  False
2  False  False  False
3   True  False   True

In [ ]:
df.isnull()*1

col1  col2  col3
0     0     0     0
1     0     1     0
2     0     0     0
3     1     0     1

In [ ]:
df.fillna('Missing')

col1     col2     col3
0      1.0      3.0        a
1      2.0  Missing        b
2      3.0      6.0        c
3  Missing      7.0  Missing

In [ ]:
df.fillna(df.mean()) #Se cambian los datos nulos por la media o cualquier otra operación matemáticas

<ipython-input-87-a2478f315f9e>:1: FutureWarning: The default value of numeric_only in DataFrame.mean is deprecated. In a future version, it will default to False. In addition, specifying 'numeric_only=None' is deprecated. Select only valid columns or specify the value of numeric_only to silence this warning.
  df.fillna(df.mean())


col1      col2  col3
0   1.0  3.000000     a
1   2.0  5.333333     b
2   3.0  6.000000     c
3   2.0  7.000000  None

In [ ]:
df.interpolate() #Interpola los datos nulos.

col1  col2  col3
0   1.0   3.0     a
1   2.0   4.5     b
2   3.0   6.0     c
3   3.0   7.0  None

In [ ]:
df.dropna() #Elimina los datos nulos.

col1  col2 col3
0   1.0   3.0    a
2   3.0   6.0    c

### 2.7 Filtrado por condiciones

In [ ]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [ ]:
df_books['Year'] > 2016

0      False
1      False
2       True
3       True
4       True
       ...  
545     True
546    False
547     True
548     True
549     True
Name: Year, Length: 550, dtype: bool

In [ ]:
mayor_a_2016 = df_books['Year'] > 2016

In [ ]:
df_books[mayor_a_2016]

Name  \
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
7                       A Gentleman in Moscow: A Novel   
8        A Higher Loyalty: Truth, Lies, and Leadership   
..                                                 ...   
544                                             Wonder   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
7                 Amor Towles          4.7    19699     15  2017      Fiction  
8                 James Comey          4.7     5983      3  2018  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
544             R. J. Palacio          4.8    21625      9  2017      Fiction  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[150 rows x 7 columns]

In [ ]:
genre_fiction = df_books['Genre'] == 'Fiction'

In [ ]:
df_books[genre_fiction & mayor_a_2016]

Name             Author  \
3                               1984 (Signet Classics)      George Orwell   
7                       A Gentleman in Moscow: A Novel        Amor Towles   
10                           A Man Called Ove: A Novel    Fredrik Backman   
13                    A Wrinkle in Time (Time Quintet)  Madeleine L'Engle   
40            Brown Bear, Brown Bear, What Do You See?    Bill Martin Jr.   
..                                                 ...                ...   
509                              To Kill a Mockingbird         Harper Lee   
529  What Should Danny Do? (The Power to Choose Ser...          Adir Levy   
534                            Where the Crawdads Sing        Delia Owens   
544                                             Wonder      R. J. Palacio   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)        Jeff Kinney   

     User Rating  Reviews  Price  Year    Genre  
3            4.7    21424      6  2017  Fiction  
7            4.7    19699     15  2017  Fiction  
10           4.6    23848      8  2017  Fiction  
13           4.5     5153      5  2018  Fiction  
40           4.9    14344      5  2017  Fiction  
..           ...      ...    ...   ...      ...  
509          4.8    26234      7  2019  Fiction  
529          4.8     8170     13  2019  Fiction  
534          4.8    87841     15  2019  Fiction  
544          4.8    21625      9  2017  Fiction  
545          4.9     9413      8  2019  Fiction  

[65 rows x 7 columns]

In [ ]:
df_books[~mayor_a_2016] #El símbolo ~ permite negar la condición en pandas.

Name               Author  \
0                        10-Day Green Smoothie Cleanse             JJ Smith   
1                                    11/22/63: A Novel         Stephen King   
5        A Dance with Dragons (A Song of Ice and Fire)  George R. R. Martin   
6    A Game of Thrones / A Clash of Kings / A Storm...  George R. R. Martin   
9                            A Man Called Ove: A Novel      Fredrik Backman   
..                                                 ...                  ...   
540                                             Wonder        R. J. Palacio   
541                                             Wonder        R. J. Palacio   
542                                             Wonder        R. J. Palacio   
543                                             Wonder        R. J. Palacio   
546  You Are a Badass: How to Stop Doubting Your Gr...          Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
0            4.7    17350      8  2016  Non Fiction  
1            4.6     2052     22  2011      Fiction  
5            4.4    12643     11  2011      Fiction  
6            4.7    19735     30  2014      Fiction  
9            4.6    23848      8  2016      Fiction  
..           ...      ...    ...   ...          ...  
540          4.8    21625      9  2013      Fiction  
541          4.8    21625      9  2014      Fiction  
542          4.8    21625      9  2015      Fiction  
543          4.8    21625      9  2016      Fiction  
546          4.7    14331      8  2016  Non Fiction  

[400 rows x 7 columns]

###2.8 Funciones principales de Pandas

In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

info() nos muestra la información del dataFrame

In [ ]:
df_books.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 550 entries, 0 to 549
Data columns (total 7 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Name         550 non-null    object 
 1   Author       550 non-null    object 
 2   User Rating  550 non-null    float64
 3   Reviews      550 non-null    int64  
 4   Price        550 non-null    int64  
 5   Year         550 non-null    int64  
 6   Genre        550 non-null    object 
dtypes: float64(1), int64(3), object(3)
memory usage: 30.2+ KB


describe() de las columnas numéricas, me dará ciertos datos estadísticos.

In [ ]:
df_books.describe()

User Rating       Reviews       Price         Year
count   550.000000    550.000000  550.000000   550.000000
mean      4.618364  11953.281818   13.100000  2014.000000
std       0.226980  11731.132017   10.842262     3.165156
min       3.300000     37.000000    0.000000  2009.000000
25%       4.500000   4058.000000    7.000000  2011.000000
50%       4.700000   8580.000000   11.000000  2014.000000
75%       4.800000  17253.250000   16.000000  2017.000000
max       4.900000  87841.000000  105.000000  2019.000000

In [ ]:
df_books.tail(2) #lo mismo que head, solo que nos devuelve los últimos dos registros.

Name       Author  \
548  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   
549  You Are a Badass: How to Stop Doubting Your Gr...  Jen Sincero   

     User Rating  Reviews  Price  Year        Genre  
548          4.7    14331      8  2018  Non Fiction  
549          4.7    14331      8  2019  Non Fiction

In [ ]:
df_books.memory_usage(deep=True) #Para saber cuanto ocupa en memoria el dataFrame

Index            128
Name           59737
Author         39078
User Rating     4400
Reviews         4400
Price           4400
Year            4400
Genre          36440
dtype: int64

el método value_count() nos permite contar cuantos datos hay de esa columna.

In [ ]:
df_books['Author'].value_counts()

Jeff Kinney                           12
Gary Chapman                          11
Rick Riordan                          11
Suzanne Collins                       11
American Psychological Association    10
                                      ..
Keith Richards                         1
Chris Cleave                           1
Alice Schertle                         1
Celeste Ng                             1
Adam Gasiewski                         1
Name: Author, Length: 248, dtype: int64

drop_duplicates() nos permite eliminar filas duplicadas

In [ ]:
df_books.iloc[0]

Name           10-Day Green Smoothie Cleanse
Author                              JJ Smith
User Rating                              4.7
Reviews                                17350
Price                                      8
Year                                    2016
Genre                            Non Fiction
Name: 0, dtype: object

In [ ]:
df_books = df_books.append(df_books.iloc[0])

<ipython-input-109-c6130e308d71>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  df_books = df_books.append(df_books.iloc[0])


In [ ]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[551 rows x 7 columns]

In [ ]:
df_books.drop_duplicates()

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
..                        ...          ...      ...    ...   ...          ...  
545               Jeff Kinney          4.9     9413      8  2019      Fiction  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  

[550 rows x 7 columns]

In [ ]:
df_books.drop_duplicates(keep='last') #con keep le decimos que elimine el primer duplicado y solo deje el último.

Name  \
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
5        A Dance with Dragons (A Song of Ice and Fire)   
..                                                 ...   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   
0                        10-Day Green Smoothie Cleanse   

                       Author  User Rating  Reviews  Price  Year        Genre  
1                Stephen King          4.6     2052     22  2011      Fiction  
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3               George Orwell          4.7    21424      6  2017      Fiction  
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction  
5         George R. R. Martin          4.4    12643     11  2011      Fiction  
..                        ...          ...      ...    ...   ...          ...  
546               Jen Sincero          4.7    14331      8  2016  Non Fiction  
547               Jen Sincero          4.7    14331      8  2017  Non Fiction  
548               Jen Sincero          4.7    14331      8  2018  Non Fiction  
549               Jen Sincero          4.7    14331      8  2019  Non Fiction  
0                    JJ Smith          4.7    17350      8  2016  Non Fiction  

[550 rows x 7 columns]

sort_values('name_columns') ordena por columnas.

* ascending = False (ordena de mayor a menor)

* ascending = True (ordena de menor a mayor)

In [ ]:
df_books.sort_values('Year',ascending=False)

Name                 Author  \
179                       If Animals Kissed Good Night      Ann Whitford Paul   
294  School Zone - Big Preschool Workbook - Ages 4 ...            School Zone   
263    P is for Potty! (Sesame Street) (Lift-the-Flap)        Naomi Kleinberg   
489                   The Wonderful Things You Will Be  Emily Winfield Martin   
267             Player's Handbook (Dungeons & Dragons)       Wizards RPG Team   
..                                                 ...                    ...   
160                  Have a Little Faith: A True Story            Mitch Albom   
512                             True Compass: A Memoir      Edward M. Kennedy   
513               Twilight (The Twilight Saga, Book 1)        Stephenie Meyer   
78   Divine Soul Mind Body Healing and Transmission...           Zhi Gang Sha   
459        The Shack: Where Tragedy Confronts Eternity       William P. Young   

     User Rating  Reviews  Price  Year        Genre  
179          4.8    16643      4  2019      Fiction  
294          4.8    23047      6  2019  Non Fiction  
263          4.7    10820      5  2019  Non Fiction  
489          4.9     8842     10  2019      Fiction  
267          4.8    16990     27  2019      Fiction  
..           ...      ...    ...   ...          ...  
160          4.8     1930      4  2009  Non Fiction  
512          4.5      438     15  2009  Non Fiction  
513          4.7    11676      9  2009      Fiction  
78           4.6       37      6  2009  Non Fiction  
459          4.6    19720      8  2009      Fiction  

[551 rows x 7 columns]

### 2.9 Groupby

In [5]:
df_books.head(2)

Name        Author  User Rating  Reviews  Price  \
0  10-Day Green Smoothie Cleanse      JJ Smith          4.7    17350      8   
1              11/22/63: A Novel  Stephen King          4.6     2052     22   

   Year        Genre  
0  2016  Non Fiction  
1  2011      Fiction

In [7]:
df_books.groupby('Author').count()

Name  User Rating  Reviews  Price  Year  Genre
Author                                                                    
Abraham Verghese               2            2        2      2     2      2
Adam Gasiewski                 1            1        1      1     1      1
Adam Mansbach                  1            1        1      1     1      1
Adir Levy                      1            1        1      1     1      1
Admiral William H. McRaven     1            1        1      1     1      1
...                          ...          ...      ...    ...   ...    ...
Walter Isaacson                3            3        3      3     3      3
William Davis                  2            2        2      2     2      2
William P. Young               2            2        2      2     2      2
Wizards RPG Team               3            3        3      3     3      3
Zhi Gang Sha                   2            2        2      2     2      2

[248 rows x 6 columns]

In [8]:
df_books.groupby('Author').mean()

<ipython-input-8-b6a0de8d28d9>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.mean is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').mean()


User Rating       Reviews      Price         Year
Author                                                                       
Abraham Verghese               4.600000   4866.000000  11.000000  2010.500000
Adam Gasiewski                 4.400000   3113.000000   6.000000  2017.000000
Adam Mansbach                  4.800000   9568.000000   9.000000  2011.000000
Adir Levy                      4.800000   8170.000000  13.000000  2019.000000
Admiral William H. McRaven     4.700000  10199.000000  11.000000  2017.000000
...                                 ...           ...        ...          ...
Walter Isaacson                4.566667   6222.666667  20.333333  2013.333333
William Davis                  4.400000   7497.000000   6.000000  2012.500000
William P. Young               4.600000  19720.000000   8.000000  2013.000000
Wizards RPG Team               4.800000  16990.000000  27.000000  2018.000000
Zhi Gang Sha                   4.600000    128.500000  11.500000  2011.000000

[248 rows x 4 columns]

In [9]:
df_books.groupby('Author').min()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                            User Rating  Reviews  Price  Year        Genre  
Author                                                                      
Abraham Verghese                    4.6     4866     11  2010      Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Non Fiction  
Adam Mansbach                       4.8     9568      9  2011      Fiction  
Adir Levy                           4.8     8170     13  2019      Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Non Fiction  
...                                 ...      ...    ...   ...          ...  
Walter Isaacson                     4.5     3014     20  2011  Non Fiction  
William Davis                       4.4     7497      6  2012  Non Fiction  
William P. Young                    4.6    19720      8  2009      Fiction  
Wizards RPG Team                    4.8    16990     27  2017      Fiction  
Zhi Gang Sha                        4.6       37      6  2009  Non Fiction  

[248 rows x 6 columns]

In [10]:
df_books.groupby('Author').max()

Name  \
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                            User Rating  Reviews  Price  Year        Genre  
Author                                                                      
Abraham Verghese                    4.6     4866     11  2011      Fiction  
Adam Gasiewski                      4.4     3113      6  2017  Non Fiction  
Adam Mansbach                       4.8     9568      9  2011      Fiction  
Adir Levy                           4.8     8170     13  2019      Fiction  
Admiral William H. McRaven          4.7    10199     11  2017  Non Fiction  
...                                 ...      ...    ...   ...          ...  
Walter Isaacson                     4.6     7827     21  2017  Non Fiction  
William Davis                       4.4     7497      6  2013  Non Fiction  
William P. Young                    4.6    19720      8  2017      Fiction  
Wizards RPG Team                    4.8    16990     27  2019      Fiction  
Zhi Gang Sha                        4.6      220     17  2013  Non Fiction  

[248 rows x 6 columns]

In [11]:
df_books.groupby('Author').sum()

<ipython-input-11-af849977d3fa>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').sum()


User Rating  Reviews  Price  Year
Author                                                       
Abraham Verghese                    9.2     9732     22  4021
Adam Gasiewski                      4.4     3113      6  2017
Adam Mansbach                       4.8     9568      9  2011
Adir Levy                           4.8     8170     13  2019
Admiral William H. McRaven          4.7    10199     11  2017
...                                 ...      ...    ...   ...
Walter Isaacson                    13.7    18668     61  6040
William Davis                       8.8    14994     12  4025
William P. Young                    9.2    39440     16  4026
Wizards RPG Team                   14.4    50970     81  6054
Zhi Gang Sha                        9.2      257     23  4022

[248 rows x 4 columns]

In [12]:
df_books.groupby('Author').sum().loc['William Davis']

<ipython-input-12-4b4655dcf6dc>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').sum().loc['William Davis']


User Rating        8.8
Reviews        14994.0
Price             12.0
Year            4025.0
Name: William Davis, dtype: float64

In [13]:
df_books.groupby('Author').sum().reset_index()

<ipython-input-13-ecb9159ebf61>:1: FutureWarning: The default value of numeric_only in DataFrameGroupBy.sum is deprecated. In a future version, numeric_only will default to False. Either specify numeric_only or select only columns which should be valid for the function.
  df_books.groupby('Author').sum().reset_index()


Author  User Rating  Reviews  Price  Year
0              Abraham Verghese          9.2     9732     22  4021
1                Adam Gasiewski          4.4     3113      6  2017
2                 Adam Mansbach          4.8     9568      9  2011
3                     Adir Levy          4.8     8170     13  2019
4    Admiral William H. McRaven          4.7    10199     11  2017
..                          ...          ...      ...    ...   ...
243             Walter Isaacson         13.7    18668     61  6040
244               William Davis          8.8    14994     12  4025
245            William P. Young          9.2    39440     16  4026
246            Wizards RPG Team         14.4    50970     81  6054
247                Zhi Gang Sha          9.2      257     23  4022

[248 rows x 5 columns]

In [14]:
df_books.groupby('Author').agg(['min','max'])

Name  \
                                                                          min   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                             Leonardo da Vinci   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Divine Soul Mind Body Healing and Transmission...   

                                                                               \
                                                                          max   
Author                                                                          
Abraham Verghese                                            Cutting for Stone   
Adam Gasiewski              Milk and Vine: Inspirational Quotes From Class...   
Adam Mansbach                                            Go the F**k to Sleep   
Adir Levy                   What Should Danny Do? (The Power to Choose Ser...   
Admiral William H. McRaven  Make Your Bed: Little Things That Can Change Y...   
...                                                                       ...   
Walter Isaacson                                                    Steve Jobs   
William Davis               Wheat Belly: Lose the Wheat, Lose the Weight, ...   
William P. Young                  The Shack: Where Tragedy Confronts Eternity   
Wizards RPG Team                       Player's Handbook (Dungeons & Dragons)   
Zhi Gang Sha                Soul Healing Miracles: Ancient and New Sacred ...   

                           User Rating      Reviews        Price      Year  \
                                   min  max     min    max   min max   min   
Author                                                                       
Abraham Verghese                   4.6  4.6    4866   4866    11  11  2010   
Adam Gasiewski                     4.4  4.4    3113   3113     6   6  2017   
Adam Mansbach                      4.8  4.8    9568   9568     9   9  2011   
Adir Levy                          4.8  4.8    8170   8170    13  13  2019   
Admiral William H. McRaven         4.7  4.7   10199  10199    11  11  2017   
...                                ...  ...     ...    ...   ...  ..   ...   
Walter Isaacson                    4.5  4.6    3014   7827    20  21  2011   
William Davis                      4.4  4.4    7497   7497     6   6  2012   
William P. Young                   4.6  4.6   19720  19720     8   8  2009   
Wizards RPG Team                   4.8  4.8   16990  16990    27  27  2017   
Zhi Gang Sha                       4.6  4.6      37    220     6  17  2009   

                                        Genre               
                             max          min          max  
Author                                                      
Abraham Verghese            2011      Fiction      Fiction  
Adam Gasiewski              2017  Non Fiction  Non Fiction  
Adam Mansbach               2011      Fiction      Fiction  
Adir Levy                   2019      Fiction      Fiction  
Admiral William H. McRaven  2017  Non Fiction  Non Fiction  
...                          ...          ...          ...  
Walter Isaacson             2017  Non Fiction  Non Fiction  
William Davis               2013  Non Fiction  Non Fiction  
William P. Young            2017      F

In [15]:
df_books.groupby('Author').agg({'Reviews':['min','max'],'User Rating':'sum'})

Reviews        User Rating
                               min    max         sum
Author                                               
Abraham Verghese              4866   4866         9.2
Adam Gasiewski                3113   3113         4.4
Adam Mansbach                 9568   9568         4.8
Adir Levy                     8170   8170         4.8
Admiral William H. McRaven   10199  10199         4.7
...                            ...    ...         ...
Walter Isaacson               3014   7827        13.7
William Davis                 7497   7497         8.8
William P. Young             19720  19720         9.2
Wizards RPG Team             16990  16990        14.4
Zhi Gang Sha                    37    220         9.2

[248 rows x 3 columns]

In [16]:
df_books.groupby(['Author','Year']).count()

Name  User Rating  Reviews  Price  Genre
Author           Year                                          
Abraham Verghese 2010     1            1        1      1      1
                 2011     1            1        1      1      1
Adam Gasiewski   2017     1            1        1      1      1
Adam Mansbach    2011     1            1        1      1      1
Adir Levy        2019     1            1        1      1      1
...                     ...          ...      ...    ...    ...
Wizards RPG Team 2017     1            1        1      1      1
                 2018     1            1        1      1      1
                 2019     1            1        1      1      1
Zhi Gang Sha     2009     1            1        1      1      1
                 2013     1            1        1      1      1

[493 rows x 5 columns]

### 2.10 Combinando DataFrames
Las Operaciones de conjuntos que podemos realizar con los DataFrames son:

<img src="https://www.golinuxcloud.com/wp-content/uploads/types_joins.png" width=600>

In [24]:
df1 = pd.DataFrame({'A':['A0','A1','A2','A3'],
 'B':['B0','B1','B2','B3'],
 'C':['C0','C1','C2','C3'],
 'D':['D0','D1','D2','D3']})

df2 = pd.DataFrame({'A':['A4','A5','A6','A7'],
 'B':['B4','B5','B6','B'],
 'C':['C4','C5','C6','C'],
 'D':['D4','D5','D6','D']})

Concatenar diferentes dataFrames

In [20]:
pd.concat([df1,df2])

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
0  A4  B4  C4  D4
1  A5  B5  C5  D5
2  A6  B6  C6  D6
3  A7  B7  C7  D7

In [25]:
pd.concat([df1,df2],ignore_index=True) #Reorganiza los indices cuando se concatenan los dataFrames.

A   B   C   D
0  A0  B0  C0  D0
1  A1  B1  C1  D1
2  A2  B2  C2  D2
3  A3  B3  C3  D3
4  A4  B4  C4  D4
5  A5  B5  C5  D5
6  A6  B6  C6  D6
7  A7   B   C   D

In [26]:
pd.concat([df1,df2],axis=1) #Concatena columnas

A   B   C   D   A   B   C   D
0  A0  B0  C0  D0  A4  B4  C4  D4
1  A1  B1  C1  D1  A5  B5  C5  D5
2  A2  B2  C2  D2  A6  B6  C6  D6
3  A3  B3  C3  D3  A7   B   C   D

Utilizando Merge

In [31]:
izq = pd.DataFrame({'key':['k0','k1','k2','k3'],
'A':['A0','A1','A2','A3'],
'B':['B0','B1','B2','B3']})
izq

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [48]:
der = pd.DataFrame({'key':['k0','k1','k2','k3'],
'C':['C0','C1','C2','C3'],
'D':['D0','D1','D2','D4']})
der

key   C   D
0  k0  C0  D0
1  k1  C1  D1
2  k2  C2  D2
3  k3  C3  D4

In [47]:
izq.merge(der, on='key')  #Full Join

key   A   B   C    D
0  k0  A0  B0  C0   D0
1  k1  A1  B1  C1   D1
2  k2  A2  B2  C2   D2
3  k3  A3  B3  C3  D34

In [49]:
der = pd.DataFrame({'key_2':['k0','k1','k2','k3'],
'C':['C0','C1','C2','C3'],
'D':['D0','D1','D2','D4']})
der

key_2   C    D
0    k0  C0   D0
1    k1  C1   D1
2    k2  C2   D2
3    k3  C3  D34

In [50]:
izq.merge(der, left_on='key',right_on='key_2') #Full Join

key   A   B key_2   C    D
0  k0  A0  B0    k0  C0   D0
1  k1  A1  B1    k1  C1   D1
2  k2  A2  B2    k2  C2   D2
3  k3  A3  B3    k3  C3  D34

In [39]:
der = pd.DataFrame({'key_2':['k0','k1','k2',np.nan],
'C':['C0','C1','C2','C3'],
'D':['D0','D1','D2','D3']})
der

key_2   C   D
0    k0  C0  D0
1    k1  C1  D1
2    k2  C2  D2
3   NaN  C3  D3

In [41]:
izq

key   A   B
0  k0  A0  B0
1  k1  A1  B1
2  k2  A2  B2
3  k3  A3  B3

In [43]:
izq.merge(der, left_on='key',right_on='key_2',how='inner') #Inner join

key   A   B key_2   C   D
0  k0  A0  B0    k0  C0  D0
1  k1  A1  B1    k1  C1  D1
2  k2  A2  B2    k2  C2  D2

In [44]:
izq.merge(der, left_on='key',right_on='key_2',how='left') #Left join

key   A   B key_2    C    D
0  k0  A0  B0    k0   C0   D0
1  k1  A1  B1    k1   C1   D1
2  k2  A2  B2    k2   C2   D2
3  k3  A3  B3   NaN  NaN  NaN

In [45]:
izq.merge(der, left_on='key',right_on='key_2',how='right') #Right join

key    A    B key_2   C   D
0   k0   A0   B0    k0  C0  D0
1   k1   A1   B1    k1  C1  D1
2   k2   A2   B2    k2  C2  D2
3  NaN  NaN  NaN   NaN  C3  D3

Comando Join, buscará el match con los índices y únicamente con ellos.

In [10]:
izq = pd.DataFrame({'A':['A0','A1','A2'],
'B':['B0','B1','B2']},index=['k0','k1','k2'])
der = pd.DataFrame({'C':['C0','C1','C2'],
'D':['D0','D1','D2']},index=['k0','k2','k3'])

In [15]:
izq

A   B
k0  A0  B0
k1  A1  B1
k2  A2  B2

In [16]:
der

C   D
k0  C0  D0
k2  C1  D1
k3  C2  D2

In [14]:
izq.join(der) #lef join con índices

A   B    C    D
k0  A0  B0   C0   D0
k1  A1  B1  NaN  NaN
k2  A2  B2   C1   D1

In [17]:
izq.join(der,how='inner') #inner join con índices

A   B   C   D
k0  A0  B0  C0  D0
k2  A2  B2  C1  D1

In [18]:
izq.join(der,how='right') #right join con índices

A    B   C   D
k0   A0   B0  C0  D0
k2   A2   B2  C1  D1
k3  NaN  NaN  C2  D2

In [19]:
izq.join(der,how='outer') #outer join con índices

A    B    C    D
k0   A0   B0   C0   D0
k1   A1   B1  NaN  NaN
k2   A2   B2   C1   D1
k3  NaN  NaN   C2   D2

### 2.11 Pivot Table
Cambiar la estructura de nuestro DataFrame de acuerdo a nuestras necesidades.



In [26]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [28]:
df_books.pivot_table(index='Author', columns='Genre',values='User Rating')

Genre                       Fiction  Non Fiction
Author                                          
Abraham Verghese                4.6          NaN
Adam Gasiewski                  NaN     4.400000
Adam Mansbach                   4.8          NaN
Adir Levy                       4.8          NaN
Admiral William H. McRaven      NaN     4.700000
...                             ...          ...
Walter Isaacson                 NaN     4.566667
William Davis                   NaN     4.400000
William P. Young                4.6          NaN
Wizards RPG Team                4.8          NaN
Zhi Gang Sha                    NaN     4.600000

[248 rows x 2 columns]

In [29]:
df_books.pivot_table(index='Genre',columns='Year', values='User Rating',aggfunc='sum')

Year          2009   2010   2011   2012   2013   2014   2015   2016   2017  \
Genre                                                                        
Fiction      110.2   92.3   97.0   94.4  109.1  134.3   79.1   89.6  113.7   
Non Fiction  119.0  135.6  130.9  132.2  118.6   96.8  153.3  144.3  119.3   

Year          2018   2019  
Genre                      
Fiction       99.5   96.4  
Non Fiction  133.9  140.6

###2.12 Melt
El método melt toma las columnas del DataFrame y las pasa a filas, con dos nuevas columnas para especificar la antigua columna y el valor que traía.

In [30]:
df_books[['Name','Genre']].head(5)

Name        Genre
0                      10-Day Green Smoothie Cleanse  Non Fiction
1                                  11/22/63: A Novel      Fiction
2            12 Rules for Life: An Antidote to Chaos  Non Fiction
3                             1984 (Signet Classics)      Fiction
4  5,000 Awesome Facts (About Everything!) (Natio...  Non Fiction

In [31]:
df_books[['Name','Genre']].head(5).melt()

variable                                              value
0     Name                      10-Day Green Smoothie Cleanse
1     Name                                  11/22/63: A Novel
2     Name            12 Rules for Life: An Antidote to Chaos
3     Name                             1984 (Signet Classics)
4     Name  5,000 Awesome Facts (About Everything!) (Natio...
5    Genre                                        Non Fiction
6    Genre                                            Fiction
7    Genre                                        Non Fiction
8    Genre                                            Fiction
9    Genre                                        Non Fiction

In [33]:
df_books.melt(id_vars='Year',value_vars='Genre')

Year variable        value
0    2016    Genre  Non Fiction
1    2011    Genre      Fiction
2    2018    Genre  Non Fiction
3    2017    Genre      Fiction
4    2019    Genre  Non Fiction
..    ...      ...          ...
545  2019    Genre      Fiction
546  2016    Genre  Non Fiction
547  2017    Genre  Non Fiction
548  2018    Genre  Non Fiction
549  2019    Genre  Non Fiction

[550 rows x 3 columns]

###2.13 Apply
Es un método que nos permite agregar funciones al dataFrame, se podría decir que se parece a las funciones de orden superior, pero en DataFrames.


In [36]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  
0                  JJ Smith          4.7    17350      8  2016  Non Fiction  
1              Stephen King          4.6     2052     22  2011      Fiction  
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction  
3             George Orwell          4.7    21424      6  2017      Fiction  
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction

In [34]:
def two_times(value):
  return value * 2

In [37]:
df_books['User Rating'].apply(two_times)

0      9.4
1      9.2
2      9.4
3      9.4
4      9.6
      ... 
545    9.8
546    9.4
547    9.4
548    9.4
549    9.4
Name: User Rating, Length: 550, dtype: float64

In [38]:
df_books['Rating_2'] = df_books['User Rating'].apply(two_times)

In [40]:
df_books['Rating_2'] = df_books['User Rating'].apply(lambda x:x*3)

In [41]:
df_books.head(5)

Name  \
0                      10-Day Green Smoothie Cleanse   
1                                  11/22/63: A Novel   
2            12 Rules for Life: An Antidote to Chaos   
3                             1984 (Signet Classics)   
4  5,000 Awesome Facts (About Everything!) (Natio...   

                     Author  User Rating  Reviews  Price  Year        Genre  \
0                  JJ Smith          4.7    17350      8  2016  Non Fiction   
1              Stephen King          4.6     2052     22  2011      Fiction   
2        Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3             George Orwell          4.7    21424      6  2017      Fiction   
4  National Geographic Kids          4.8     7665     12  2019  Non Fiction   

   Rating_2  
0      14.1  
1      13.8  
2      14.1  
3      14.1  
4      14.4

In [43]:
df_books['Rating_2'] = df_books.apply(lambda x: x['User Rating'] * 2 if x['Genre'] == 'Fiction' else x['User Rating'],axis=1)

In [44]:
df_books

Name  \
0                        10-Day Green Smoothie Cleanse   
1                                    11/22/63: A Novel   
2              12 Rules for Life: An Antidote to Chaos   
3                               1984 (Signet Classics)   
4    5,000 Awesome Facts (About Everything!) (Natio...   
..                                                 ...   
545       Wrecking Ball (Diary of a Wimpy Kid Book 14)   
546  You Are a Badass: How to Stop Doubting Your Gr...   
547  You Are a Badass: How to Stop Doubting Your Gr...   
548  You Are a Badass: How to Stop Doubting Your Gr...   
549  You Are a Badass: How to Stop Doubting Your Gr...   

                       Author  User Rating  Reviews  Price  Year        Genre  \
0                    JJ Smith          4.7    17350      8  2016  Non Fiction   
1                Stephen King          4.6     2052     22  2011      Fiction   
2          Jordan B. Peterson          4.7    18979     15  2018  Non Fiction   
3               George Orwell          4.7    21424      6  2017      Fiction   
4    National Geographic Kids          4.8     7665     12  2019  Non Fiction   
..                        ...          ...      ...    ...   ...          ...   
545               Jeff Kinney          4.9     9413      8  2019      Fiction   
546               Jen Sincero          4.7    14331      8  2016  Non Fiction   
547               Jen Sincero          4.7    14331      8  2017  Non Fiction   
548               Jen Sincero          4.7    14331      8  2018  Non Fiction   
549               Jen Sincero          4.7    14331      8  2019  Non Fiction   

     Rating_2  
0         4.7  
1         9.2  
2         4.7  
3         9.4  
4         4.8  
..        ...  
545       9.8  
546       4.7  
547       4.7  
548       4.7  
549       4.7  

[550 rows x 8 columns]