# Operaciones básicas de matriz con Numpy🧮
Esta sección cubre sumas, restas, multiplicaciones, divisiones y más.

In [1]:
import numpy as np

<img src="https://numpy.org/doc/stable/_images/np_matrix_broadcasting.png">

In [ ]:
a = np.array([np.arange(1,5),np.arange(20,24)])
a

array([[ 1,  2,  3,  4],
       [20, 21, 22, 23]])

In [ ]:
b = np.ones((2,4),dtype="int32")
b

array([[1, 1, 1, 1],
       [1, 1, 1, 1]])

In [ ]:
a + b #Suma de matrices

array([[ 2,  3,  4,  5],
       [21, 22, 23, 24]])

In [ ]:
a - b #Resta de matrices

array([[ 0,  1,  2,  3],
       [19, 20, 21, 22]])

In [ ]:
a * b #Multiplicación de matrices

array([[ 1,  2,  3,  4],
       [20, 21, 22, 23]])

In [ ]:
a / b #División de matrices

array([[ 1.,  2.,  3.,  4.],
       [20., 21., 22., 23.]])

## Sumatoria de elementos

In [ ]:
a.sum() #Default, suma todos los elementos de la matrices.

96

In [ ]:
a.sum(axis=0) #Suma solo las columnas

array([21, 23, 25, 27])

In [ ]:
a.sum(axis=1) #Suma solo las filas

array([10, 86])

## Producto Escalar

In [ ]:
a

array([[ 1,  2,  3,  4],
       [20, 21, 22, 23]])

In [ ]:
a * 2

array([[ 2,  4,  6,  8],
       [40, 42, 44, 46]])

# Operaciones de matriz más útiles 🧑‍🔬🧠
Esta sección cubre máximo, mínimo, suma, media, producto, desviación estándar y más

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation.png">

<img src="https://numpy.org/doc/stable/_images/np_matrix_aggregation_row.png">

In [ ]:
a = np.array([[0.45053314, 0.17296777, 0.34376245, 0.5510652],
              [0.54627315, 0.05093587, 0.40067661, 0.55645993],
              [0.12697628, 0.82485143, 0.26590556, 0.56917101]])

In [ ]:
a.sum()

4.8595784

In [ ]:
a.max() #Trae el dato más grande de la matriz

0.82485143

In [ ]:
a.max(axis=0) #Encuentra el mayor de cada columna

array([0.54627315, 0.82485143, 0.40067661, 0.56917101])

In [ ]:
a.max(axis=1) #Encuentra el mayor de cada fila

array([0.5510652 , 0.55645993, 0.82485143])

In [ ]:
a.min() #Trae el dato más pequeño de la matriz, al igual que que max podemos encontrar el min por fila y columna.

0.05093587

## Generar números aleatorios

In [ ]:
a_rand = np.random.random((3,2,3)) #Los números están en el rango [0,1)

In [ ]:
a_rand

array([[[0.33831789, 0.50024697, 0.94628129],
        [0.62803167, 0.7908523 , 0.07457066]],

       [[0.60193675, 0.61083423, 0.32835821],
        [0.99464995, 0.43230278, 0.24431742]],

       [[0.83866818, 0.35581608, 0.81439501],
        [0.44611245, 0.71511959, 0.50399673]]])

In [ ]:
random_rand = np.random.rand() #Genera solo un número aleatorio en el rango [0,1)
random_rand

0.2077438820341544

In [ ]:
random03 = np.random.randint(0,10,size=(4,4))
random03

array([[0, 5, 6, 5],
       [5, 9, 6, 1],
       [4, 9, 8, 6],
       [3, 6, 6, 3]])

## Cómo obtener artículos únicos y recuentos
Esta sección cubre np.unique(), funciona para vectores y matrices

In [ ]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [ ]:
val_unicos, conteo_repetidos = np.unique(a, return_counts = True) #Si solo queremos los valores únicos, quitamos el segundo parámetro
val_unicos

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [ ]:
conteo_repetidos

array([3, 2, 2, 2, 1, 1, 1, 1, 1, 1], dtype=int64)

In [ ]:
list(zip(val_unicos,conteo_repetidos))

[(11, 3),
 (12, 2),
 (13, 2),
 (14, 2),
 (15, 1),
 (16, 1),
 (17, 1),
 (18, 1),
 (19, 1),
 (20, 1)]

In [ ]:
a_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [1, 2, 3, 4]])
a_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [ 1,  2,  3,  4]])

In [ ]:
a_2d_unicos = np.unique(a_2d)
print(a_2d_unicos)
print(a_2d_unicos.shape) #IMPORTANTE! Al sacar los repetidos, se convierte en un array

[ 1  2  3  4  5  6  7  8  9 10 11 12]
(12,)


In [ ]:
a_2d_unicos_columns = np.unique(a_2d,axis=0) #Se especifica que se encuentre los valores únicos por columna
a_2d_unicos_columns

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
a_2d = np.array([[1, 2, 4, 4], [5, 6, 8, 8], [9, 10, 12, 12], [1, 2, 4, 4]])
a_2d

array([[ 1,  2,  4,  4],
       [ 5,  6,  8,  8],
       [ 9, 10, 12, 12],
       [ 1,  2,  4,  4]])

In [ ]:
a_2d_unicos_rows = np.unique(a_2d,axis=1) #Se especifica que se encuentre los valores únicos por columna
a_2d_unicos_rows

array([[ 1,  2,  4],
       [ 5,  6,  8],
       [ 9, 10, 12],
       [ 1,  2,  4]])

## Transponer y remodelar una matriz
<img src="https://numpy.org/doc/stable/_images/np_transposing_reshaping.png">

In [ ]:
data = np.arange(1,7)
data

array([1, 2, 3, 4, 5, 6])

In [ ]:
data.shape

(6,)

In [ ]:
data.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [ ]:
data.reshape(2,3).T

array([[1, 4],
       [2, 5],
       [3, 6]])

## Cómo invertir una matriz
Esta sección cubre np.flip()

In [2]:
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])
arr

array([1, 2, 3, 4, 5, 6, 7, 8])

In [3]:
arr_invertido = np.flip(arr)
arr_invertido

array([8, 7, 6, 5, 4, 3, 2, 1])

In [13]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr_2d

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [5]:
arr_2d_invertido = np.flip(arr_2d)
arr_2d_invertido #Invierto totalmente la matriz, tanto columnas como filas.

array([[12, 11, 10,  9],
       [ 8,  7,  6,  5],
       [ 4,  3,  2,  1]])

In [6]:
arr_2d_invertido = np.flip(arr_2d,axis=0) #Solo se invierten las columnas
arr_2d_invertido

array([[ 9, 10, 11, 12],
       [ 5,  6,  7,  8],
       [ 1,  2,  3,  4]])

In [8]:
arr_2d_invertido = np.flip(arr_2d,axis=1) #Solo se invierten las filas
arr_2d_invertido

array([[ 4,  3,  2,  1],
       [ 8,  7,  6,  5],
       [12, 11, 10,  9]])

In [10]:
arr_2d[1] = np.flip(arr_2d[1]) #Invertir solo una fila
arr_2d

array([[ 1,  2,  3,  4],
       [ 8,  7,  6,  5],
       [ 9, 10, 11, 12]])

In [15]:
arr_2d[:,1] = np.flip(arr_2d[:,1]) #Invertir solo una columna
arr_2d

array([[ 1, 10,  3,  4],
       [ 8,  7,  6,  5],
       [ 9,  2, 11, 12]])

## Reformar y aplanar matrices multimensionales.
Uso de flateen() y ravel(). La diferencia entre ambos es que ravel() los cambios afectarán a la matriz principal.

In [21]:
x = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
x

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [20]:
x.size

12

In [22]:
x.flatten() #Aplana una matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [23]:
x.ravel() #Aplana una matriz

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [30]:
x_ref = x.flatten()
x_ref[0] = 10000 #Referencia
x_ref,x #No afectada la matriz principal

(array([10000,     2,     3,     4,     5,     6,     7,     8,     9,
           10,    11,    12]),
 array([[10000,     2,     3,     4],
        [    5,     6,     7,     8],
        [    9,    10,    11,    12]]))

In [31]:
x_ref = x.ravel()
x_ref[0] = 10000 #Referencia
x_ref,x #Afectada la matriz principal

(array([10000,     2,     3,     4,     5,     6,     7,     8,     9,
           10,    11,    12]),
 array([[10000,     2,     3,     4],
        [    5,     6,     7,     8],
        [    9,    10,    11,    12]]))