# Manipulación y Transformación de Datos con Pandas y Numpy 📓🧮🐍

## 1. Uso de la librería Numpy

In [1]:
import numpy as np

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0]
#arr[1]
#arr[8]
#arr[9]

1

In [15]:
len(arr)

9

In [16]:
arr[0] + arr[5]

7

In [19]:
matriz[0][2]

3

In [21]:
#arr[0:4]
arr[::3]

array([1, 4, 7])

In [23]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [28]:
matriz_tridimensional = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [29]:
matriz_tridimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [30]:
#matriz_tridimensional[0]
matriz_tridimensional[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matriz_tridimensional[2][2][2]

27

In [38]:
matriz_tridimensional[1:,:,0:2]

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])