In [5]:
import numpy as np

In [6]:
a = np.array([1,2,3,4]) #Array

In [7]:
lista = [1,2,3,4]

In [8]:
a

array([1, 2, 3, 4])

In [9]:
b = np.array([[1,2,3,4],[1,2,3,4]])

In [10]:
b

array([[1, 2, 3, 4],
       [1, 2, 3, 4]])

In [11]:
a[2]
a[0]+a[2] #0 + 3

4

In [12]:
b[1]
b[1][2]
b[1][1:]

array([2, 3, 4])

# Cómo crear una matriz básica

<img src="https://numpy.org/doc/stable/_images/np_array.png">

In [13]:
a = np.array([1,2,3])

In [18]:
#np.zeros(2) #Crear Array de ceros
#np.zeros(5)
#np.zeros((5,2)) #Crear matriz de ceros
np.zeros((5,2,3)) #Crear tensor de ceros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [23]:
#np.ones(2)#Crear Array de 1`s
#np.ones((2,2)) #Crear Matriz de 1`s
np.ones((2,2,2)) #Crear Tensor de 1`s

array([[[1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.]]])

In [31]:
#np.arange(4) #Solo crea arreglos UNIDEMSIONAL
#np.arange(5,10) #Rango inicial y final
np.arange(5,10,0.5) #Rango inicial, final y pasos.

array([5. , 5.5, 6. , 6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

In [32]:
arr = np.arange(5,20,5)

In [35]:
arr.dtype

dtype('float32')

In [34]:
arr = np.arange(5,20,5,dtype="float32") #Convertir de int a float

In [36]:
arr

array([ 5., 10., 15.], dtype=float32)

In [41]:
arr = np.array([1.33,14.233,123.44])

In [44]:
arr.dtype

dtype('float64')

In [45]:
arr

array([  1.33 ,  14.233, 123.44 ])

In [47]:
arr = np.array(arr,dtype="int32") #Convertir de float a int

In [48]:
arr

array([  1,  14, 123])

In [49]:
string_array = np.array(['23.32','23.122','544.22'])

In [52]:
string_array

array([ 23.32 ,  23.122, 544.22 ], dtype=float32)

In [51]:
string_array = np.array(string_array,dtype="float32") #Convertir de string a float

## Linspace vs Arange (UNIDEMENSIONAL)

In [59]:
np.linspace(0,10,num=20) #indica en CUANTOS ELEMENTOS queremos llegar al límite superior

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [56]:
np.arange(0,10,0.5) #indica de CUANTO EN CUANTO queremos llegar al límite superior.

array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. ,
       6.5, 7. , 7.5, 8. , 8.5, 9. , 9.5])

## Adición, eliminación y clasificación de elementos

In [60]:
arr = np.array([2,1,5,3,7,4,6,8])

In [61]:
arr

array([2, 1, 5, 3, 7, 4, 6, 8])

In [62]:
np.sort(arr) #Ordena el array de asc

array([1, 2, 3, 4, 5, 6, 7, 8])

In [66]:
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8])

In [79]:
matriz = np.array([[10,50,30],[30,40,20]])

In [84]:
matriz

array([[10, 40, 20],
       [30, 50, 30]])

In [83]:
matriz = np.sort(matriz,axis=0) #Cuando se agrega el axis, nos permite ordenar por columnas.

In [85]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [86]:
np.concatenate((a,b)) #Concatena arrays

array([1, 2, 3, 4, 5, 6, 7, 8])

In [118]:
matriz_a = np.array([[1,2,3],[4,5,9]])

In [119]:
matriz_b = np.array([[11,22,12],[44,55,44]])

In [122]:
#np.concatenate((matriz_a,matriz_b)) #Por default se concatenan las columnas
np.concatenate((matriz_a,matriz_b),axis=1) #Se concatenan las filas si se le especifica

array([[ 1,  2,  3, 11, 22, 12],
       [ 4,  5,  9, 44, 55, 44]])

## ¿Cómo sabes la forma y el tamaño de una matriz?

In [127]:
array_example = np.array([[[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0, 1, 2, 3],
                           [4, 5, 6, 7]],

                          [[0 ,1 ,2, 3],
                           [4, 5, 6, 7]]])

In [131]:
array_example.ndim #Sabemos la dimensión de la matriz

3

In [132]:
array_example.size #Sabemos cuantos elementos tiene la matriz

24

In [133]:
array_example.shape #Sabemo la forma de la matriz

(3, 2, 4)

## ¿Puedes remodelar una matriz?

In [140]:
matriz = np.array([np.arange(1,10),np.arange(21,30)])

In [141]:
matriz

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9],
       [21, 22, 23, 24, 25, 26, 27, 28, 29]])

In [143]:
matriz.shape

(2, 9)

In [145]:
matriz.T.shape #Matriz Transpuesta

(9, 2)

In [152]:
matriz.reshape(6,3).shape

(6, 3)

In [149]:
matriz.reshape(6,3) #Remodela la matriz.

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [150]:
matriz.reshape(3,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

## Cómo convertir una matriz 1D en una matriz 2D

In [154]:
a = np.array([1,2,3,4,5,6])
a.shape

(6,)

In [155]:
a2 = a[np.newaxis,:] #Le agrega solo una dimensión a nivel de fila.

In [158]:
a2 = a[:,np.newaxis] #Le agrega solo una dimensión a nivel de columna.

In [159]:
a2.shape

(6, 1)

In [160]:
a2

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [161]:
a = np.array([1,2,3,4,5,6])

In [162]:
a.shape

(6,)

In [163]:
b = np.expand_dims(a, axis=1)
b

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [173]:
z = np.expand_dims(b,axis=1)
z

array([[[1]],

       [[2]],

       [[3]],

       [[4]],

       [[5]],

       [[6]]])

In [174]:
z.shape

(6, 1, 1)

In [164]:
c = np.expand_dims(a,axis=0)#Muy similar al np.newaxis
c

array([[1, 2, 3, 4, 5, 6]])

### Operadores Lógicos con Numpy

In [182]:
lista = [1,2,3,4,5,6]

In [183]:
lista[lista > 4] #En listas no es posible, experimento interesante.

TypeError: '>' not supported between instances of 'list' and 'int'

In [184]:
arr = np.array(lista)

In [185]:
arr[arr>4]

array([5, 6])

In [206]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [208]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

Filtrar: De esta forma podemos filtar datos que cumplan con esa condición

In [195]:
#a[a%2==0] #Numeros pares
a[(a>6) & (a%2==0)] #Numeros pares y que sean mayores que 6.   & para and y | para or

array([ 8, 10, 12])

In [210]:
#El resultado son los indices de los elementos que cumplen con esa condición
np.nonzero(a<4) #La primera matriz representa los índices de las filas y la segunda representa los índices de las columnas que cumplen con esa condición

(array([0, 0, 0], dtype=int64), array([0, 1, 2], dtype=int64))

In [214]:
b = np.nonzero(a<4)

In [215]:
lista_coordenadas = list(zip(b[0],b[1])) #Una forma de unir las coordenadas

In [216]:
lista_coordenadas

[(0, 0), (0, 1), (0, 2)]

Comprobar: De esta forma podemos comprobar que elemento cumple con esa condición

In [202]:
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [196]:
a % 2 == 0 

array([[False,  True, False,  True],
       [False,  True, False,  True],
       [False,  True, False,  True]])

In [201]:
(a % 2 == 0) & (a >= 6)

array([[False, False, False, False],
       [False,  True, False,  True],
       [False,  True, False,  True]])

¡IMPORTANTE!

In [252]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])

In [246]:
b1 = a[0][:]
b1

array([1, 2, 3, 4])

In [247]:
b1[3] = 99

In [248]:
a[0] #Vemos como se modificó el elemento original y esto lo hicimos por medio de la variable b1

array([ 1,  2,  3, 99])

In [257]:
b1 = a[0][:].copy() #De esta forma podemos realizar una copia sin modificar la parte original

In [254]:
b1

array([1, 2, 3, 4])