# Manipulación y Transformación de Datos con Pandas y Numpy 📓🧮🐍

## 1. Uso de la librería Numpy

In [1]:
import numpy as np

### 1.1 Aprendiendo sobre los arrays y matrices {bidi,tridi}.mensionales

In [2]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [3]:
arr = np.array(lista)

In [4]:
type(arr)

numpy.ndarray

In [5]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
arr[0]
#arr[1]
#arr[8]
#arr[9]

1

In [15]:
len(arr)

9

In [16]:
arr[0] + arr[5]

7

In [19]:
matriz[0][2]

3

In [21]:
#arr[0:4]
arr[::3]

array([1, 4, 7])

In [23]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [28]:
matriz_tridimensional = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [29]:
matriz_tridimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [30]:
#matriz_tridimensional[0]
matriz_tridimensional[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
matriz_tridimensional[2][2][2]

27

In [38]:
matriz_tridimensional[1:,:,0:2]

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])

### 1.2 Tipos de datos en Numpy

#### Tipo de dato int32

In [66]:
arr=np.array([0,1,2,3,4]) #método manual para crear un array del 0-4

In [67]:
arr=np.arange(0,5) #método .arange(min,max-1) para crear un array del 0-4

In [68]:
arr

array([0, 1, 2, 3, 4])

In [69]:
arr.dtype

dtype('int32')

#### Tipo de dato float64

In [ ]:
arr=np.array([1,2,3,4])

In [24]:
arr = np.array([1,2,3,4], dtype='float64') #método No.1 para castear un tipo de datos a otro tipo de datos numpy.

In [25]:
arr.astype(np.float64) #método No.2 para castear un tipo de datos a otro tipo de datos en numpy.

array([1., 2., 3., 4.])

#### Tipo de dato boole64

In [36]:
arr = np.array([0,1,2,3,4])

In [37]:
arr=arr.astype(np.bool_)

In [38]:
arr

array([False,  True,  True,  True,  True])

#### Tipo de dato string64

In [48]:
arr = np.array([0,1,2,3,4])

In [49]:
arr = arr.astype(np.string_)

In [58]:
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [56]:
arr = np.array(['0','1','2','3','4'])
#arr = np.array(['Hello','1','2','3','4']) #No puede convertir un texto a entero.

In [57]:
arr = arr.astype(np.int8) #Investigar int8 y int32

Si quieres conocer todos los tipos de datos de numpy, visita su sitio web oficial: https://numpy.org/doc/stable/user/basics.types.html

## 1.3 Dimensiones

* Scalar = Un único valor por separado (unidad).
* Vector = Una colección unidemensional de elementos del mismo tipo de datos.
* Matrix = Una colección bidimensional de elementos del mismo tipo de datos. (Filas y Columnas)
* Tensor = Una colección de n-dimension de elementos del mismo tipo de datos.

<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMjQ0/MDAxNTkwMzcxNTgxMjgx.zVM_8O3aWx1DUjeKFx-FRXeHS1KVHWfdSiOBE2--1k4g.6z_U8ssbX1lwelBEqUxjtyutk2y6HSNTvk5a7pTYIWkg.PNG.nabilera1/image.png?type=w800">

In [6]:
scalar = np.array(42)
print(scalar)

42


In [7]:
scalar.ndim #Nos permite saber cuantas dimensiones tiene nuestro objeto numpy creado.

0

In [8]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [9]:
vector.ndim

1

In [17]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [18]:
matrix.ndim

2

In [19]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [20]:
tensor.ndim

3