<a href="https://colab.research.google.com/github/OmarFloresPTY/my-google-colabs/blob/master/numpy_pandas_manipulacion_datos.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Manipulación y Transformación de Datos con Pandas y Numpy 📓🧮🐍

## 1. Uso de la librería Numpy

In [1]:
import numpy as np

### 1.1 Aprendiendo sobre los arrays y matrices {bidi,tridi}.mensionales

In [ ]:
lista = [1,2,3,4,5,6,7,8,9]
lista

[1, 2, 3, 4, 5, 6, 7, 8, 9]

In [ ]:
arr = np.array(lista)

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
matriz = [[1,2,3],[4,5,6],[7,8,9]]
matriz = np.array(matriz)
matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
arr[0]
#arr[1]
#arr[8]
#arr[9]

1

In [ ]:
len(arr)

9

In [ ]:
arr[0] + arr[5]

7

In [ ]:
matriz[0][2]

3

In [ ]:
#arr[0:4]
arr[::3]

array([1, 4, 7])

In [ ]:
matriz[1:,0:2]

array([[4, 5],
       [7, 8]])

In [ ]:
matriz_tridimensional = np.array([
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[10, 11, 12], [13, 14, 15], [16, 17, 18]],
    [[19, 20, 21], [22, 23, 24], [25, 26, 27]]
])

In [ ]:
matriz_tridimensional

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]],

       [[19, 20, 21],
        [22, 23, 24],
        [25, 26, 27]]])

In [ ]:
#matriz_tridimensional[0]
matriz_tridimensional[2]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
matriz_tridimensional[2][2][2]

27

In [ ]:
matriz_tridimensional[1:,:,0:2]

array([[[10, 11],
        [13, 14],
        [16, 17]],

       [[19, 20],
        [22, 23],
        [25, 26]]])

### 1.2 Tipos de datos en Numpy

#### Tipo de dato int32

In [ ]:
arr=np.array([0,1,2,3,4]) #método manual para crear un array del 0-4

In [ ]:
arr=np.arange(0,5) #método .arange(min,max-1) para crear un array del 0-4

In [ ]:
arr

array([0, 1, 2, 3, 4])

In [ ]:
arr.dtype

dtype('int32')

#### Tipo de dato float64

In [ ]:
arr=np.array([1,2,3,4])

In [ ]:
arr = np.array([1,2,3,4], dtype='float64') #método No.1 para castear un tipo de datos a otro tipo de datos numpy.

In [ ]:
arr.astype(np.float64) #método No.2 para castear un tipo de datos a otro tipo de datos en numpy.

array([1., 2., 3., 4.])

#### Tipo de dato boole64

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
arr=arr.astype(np.bool_)

In [ ]:
arr

array([False,  True,  True,  True,  True])

#### Tipo de dato string64

In [ ]:
arr = np.array([0,1,2,3,4])

In [ ]:
arr = arr.astype(np.string_)

In [ ]:
arr

array([0, 1, 2, 3, 4], dtype=int8)

In [ ]:
arr = np.array(['0','1','2','3','4'])
#arr = np.array(['Hello','1','2','3','4']) #No puede convertir un texto a entero.

In [ ]:
arr = arr.astype(np.int8) #Investigar int8 y int32

Si quieres conocer todos los tipos de datos de numpy, visita su sitio web oficial: https://numpy.org/doc/stable/user/basics.types.html

### 1.3 Dimensiones

* Scalar = Un único valor por separado (unidad).
* Vector = Una colección unidemensional de elementos del mismo tipo de datos.
* Matrix = Una colección bidimensional de elementos del mismo tipo de datos. (Filas y Columnas)
* Tensor = Una colección de n-dimension de elementos del mismo tipo de datos.

<img src="https://mblogthumb-phinf.pstatic.net/MjAyMDA1MjVfMjQ0/MDAxNTkwMzcxNTgxMjgx.zVM_8O3aWx1DUjeKFx-FRXeHS1KVHWfdSiOBE2--1k4g.6z_U8ssbX1lwelBEqUxjtyutk2y6HSNTvk5a7pTYIWkg.PNG.nabilera1/image.png?type=w800">

In [ ]:
scalar = np.array(42)
print(scalar)

42


In [ ]:
scalar.ndim #Nos permite saber cuantas dimensiones tiene nuestro objeto numpy creado.

0

In [ ]:
vector = np.array([1,2,3])
print(vector)

[1 2 3]


In [ ]:
vector.ndim

1

In [ ]:
matrix = np.array([[1,2,3],[4,5,6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


In [ ]:
matrix.ndim

2

In [ ]:
tensor = np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])
print(tensor)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]]]


In [ ]:
tensor.ndim

3

### 1.4 Creando arrays
Creando arrays con las diferentes funciones que tiene numpy, hasta el momento hemos creado esta estructura de datos pasando como parámetro una lista.

#### range(min,max)
* El método range(min,max)es un método creado por python pero no por numpy.

In [ ]:
list(range(0,10))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

#### np.arange(min,max-1,pasos) 
* El método np.arange(min,max-1,pasos) sí es un método creado por numpy para crear arrays desde un rango dado.

In [ ]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

#### np.zeros(n) (vector)
* El método np.zeros(n) crea un array con la cantidad de ceros indicados en n.

In [ ]:
np.zeros(3)

array([0., 0., 0.])

#### np.zeros((n,m)) (matriz)
* Crea una matriz de ceros con la sintaxis np.zeros((n,m)) ==> n y m son pasados como parámetros.

In [ ]:
#np.zeros((3,3))
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

#### np.ones((n,m))
* Crea una matriz de unos con la sintaxis np.ones((n,m)) ==> n y m son pasados como parámetros.

In [ ]:
np.ones((10,10))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

#### np.linspace(min,max,cant)
* Crea una distribución normalizada y ordenada de datos del 0 al 10 generados a partir de 100 datos.

In [ ]:
np.linspace(0,10,100) #Crea una distribución normalizada y ordenada de datos del 0 al 10 generados a partir de 100 datos.

array([ 0.        ,  0.1010101 ,  0.2020202 ,  0.3030303 ,  0.4040404 ,
        0.50505051,  0.60606061,  0.70707071,  0.80808081,  0.90909091,
        1.01010101,  1.11111111,  1.21212121,  1.31313131,  1.41414141,
        1.51515152,  1.61616162,  1.71717172,  1.81818182,  1.91919192,
        2.02020202,  2.12121212,  2.22222222,  2.32323232,  2.42424242,
        2.52525253,  2.62626263,  2.72727273,  2.82828283,  2.92929293,
        3.03030303,  3.13131313,  3.23232323,  3.33333333,  3.43434343,
        3.53535354,  3.63636364,  3.73737374,  3.83838384,  3.93939394,
        4.04040404,  4.14141414,  4.24242424,  4.34343434,  4.44444444,
        4.54545455,  4.64646465,  4.74747475,  4.84848485,  4.94949495,
        5.05050505,  5.15151515,  5.25252525,  5.35353535,  5.45454545,
        5.55555556,  5.65656566,  5.75757576,  5.85858586,  5.95959596,
        6.06060606,  6.16161616,  6.26262626,  6.36363636,  6.46464646,
        6.56565657,  6.66666667,  6.76767677,  6.86868687,  6.96

#### np.eye(n)
* Genera una matriz identidad NxN donde N es el valor pasado como parámetro.

In [ ]:
np.eye(4) 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

#### np.random
* np.random.rand() genera un escalar del 0 al 1.
* np.random.rand(n) generara un array con n cantidad de elementos del 0 al 1.
* np.rand(n,m) genera una matriz de n,m cantidad de elementos del 0 al 1.
* np.randint(min,max) genera un número aleatorio entre el min y el max.
* np.randint(min,max,(n,m)) genera un matriz de n,m de elementos aleatorios entre el min y el max.


In [ ]:
np.random.rand()

0.6906089723726002

In [ ]:
np.random.rand(4)

array([0.96685689, 0.63863924, 0.42806768, 0.03635644])

In [ ]:
np.random.rand(4,4)

array([[0.02808761, 0.43323258, 0.50477401, 0.67823693],
       [0.52756445, 0.22223687, 0.14752001, 0.8626257 ],
       [0.05345123, 0.54952941, 0.33329937, 0.81996029],
       [0.37559612, 0.80355444, 0.33105405, 0.64180839]])

In [ ]:
np.random.randint(1,15)

14

In [93]:
np.random.randint(1,100,(10,10))

array([[17, 14, 80, 33, 45, 75, 35, 61, 96, 99],
       [ 4, 49, 36, 31, 55, 77, 36, 71,  1, 24],
       [88, 75,  6, 12, 70, 22, 86,  8, 33, 50],
       [ 7, 45, 68, 94, 83, 46, 83, 45, 18, 85],
       [39, 29, 55, 96,  5, 37, 61, 77, 54,  3],
       [77,  3, 67, 46,  5, 45, 65, 76, 79, 60],
       [31, 67,  1, 85, 13,  9,  1, 80, 59,  4],
       [88, 98, 74, 66,  8, 85, 37, 65, 68, 17],
       [49, 83, 84, 38, 42, 24, 77,  6, 35, 37],
       [79, 39, 93, 67, 77, 44, 32, 63, 34, 25]])

### 1.5 Shape y Reshape
El método shape nos permite ver como está construido el objeto numpy, eso quiere decir que nos muestra las dimensiones y el reshape nos da la opción de ordenarlos de diferente forma siempre y cuando se respete la cantidad de elementos en el objeto numpy.

In [14]:
arr = np.random.randint(1,10,(3,2))

In [15]:
arr.shape

(3, 2)

In [16]:
arr

array([[6, 8],
       [1, 7],
       [7, 1]])

In [21]:
arr.reshape(1,6)
#arr.reshape(2,3)
#arr.reshape(6,1)

array([[6, 8, 1, 7, 7, 1]])

In [20]:
np.reshape(arr,(1,6))

array([[6, 8, 1, 7, 7, 1]])

In [22]:
np.reshape(arr,(2,3),'C')

array([[6, 8, 1],
       [7, 7, 1]])

In [23]:
np.reshape(arr,(2,3),'F')

array([[6, 7, 7],
       [1, 8, 1]])

In [24]:
np.reshape(arr,(2,3),'A')

array([[6, 8, 1],
       [7, 7, 1]])

### 1.6 Funciones Principales de Numpy

In [26]:
arr = np.random.randint(1,20,10)

In [33]:
arr

array([ 2,  1,  9,  5, 11, 14,  2,  6,  9, 17])

In [34]:
matriz = arr.reshape(2,5)

In [35]:
matriz

array([[ 2,  1,  9,  5, 11],
       [14,  2,  6,  9, 17]])

#### max()
max() nos trae el valor máximo de un array o de una matriz, este método se le puede pasar dos parámetro como lo son el 0 y el 1.
* max(0): Trae los valores máximos de cada columna. Devuelve un array.
* max(1): Trae los valores máximos de cada fila. Devuelve un array.

In [36]:
arr.max()

17

In [37]:
matriz.max()

17

In [40]:
matriz.max(1) #Realiza la búsqueda del mayor por fila
#matriz.max(0) #Realiza la búsqueda del mayor por columna

array([14,  2,  9,  9, 17])

#### argmax()
argmax() a diferencia del max() este solo trae la posición del valor mayor dentro de la array o matriz, este método se le puede pasar dos paráremtros como lo son el 0 y el 1.
* argmax(0): Trae los indices de los valores máximos de cada columna. Devuelve un array.
* argmax(1): Trae los indices de los valores máximos de cada fila. Devuelve un array.

In [41]:
matriz.argmax()

9

In [45]:
matriz.argmax(0) #Por columna
#matriz.argmax(1) #Por fila

array([1, 1, 0, 1, 1])

#### min()
min() nos trae el valor mínimo de un array o de una matriz, este método se le puede pasar dos parámetro como lo son el 0 y el 1.
* min(0): Trae los valores mínimos de cada columna. Devuelve un array.
* min(1): Trae los valores mínimos de cada fila. Devuelve un array.

In [46]:
arr.min()

1

In [48]:
matriz.min()

1

In [50]:
#matriz.min(0)
matriz.min(1)

array([1, 2])

#### argmin()
argmin() a diferencia del min() este solo trae la posición del valor menor dentro de la array o matriz, este método se le puede pasar dos paráremtros como lo son el 0 y el 1.
* argmin(0): Trae los indices de los valores mínimos de cada columna. Devuelve un array.
* argmax(1): Trae los indices de los valores mínimos de cada fila. Devuelve un array.

In [51]:
matriz.argmin()

1

In [52]:
matriz.argmin(0)
#matriz.argmin(1)

array([0, 0, 1, 0, 0])

#### ptp()
Calcula la diferencia entre el valor máximo y el mínimo de cada array o matriz. Al igual que los otros métodos podemos aplicarlo a las filas y a las columnas

In [57]:
arr.ptp()

16

In [58]:
matriz.ptp()

16

In [61]:
matriz

array([[ 2,  1,  9,  5, 11],
       [14,  2,  6,  9, 17]])

In [60]:
matriz.ptp(0)
#matriz.ptp(1)

array([12,  1,  3,  4,  6])

#### percentile()
Los percentiles son valores que dividen un conjunto de datos estadísticos, de forma que un porcentaje de los mismos quede por debajo de dicho valor.

In [81]:
arr.sort() #sort() es un método que nos permite ordenar los elementos.
print(arr)
matriz.sort()
print(f'=====================\n{matriz}')

[ 1  2  2  5  6  9  9 11 14 17]
[[ 1  2  2  5  6]
 [ 9  9 11 14 17]]


In [63]:
np.percentile(arr,50)

7.5

In [64]:
np.percentile(matriz,50)

7.5

#### median()
Calcula la mediana de un conjunto de datos.
Al igual que todas la funciones que hemos visto hasta aquí nos permite realizar estas operaciones de forma general, por fila y columna

In [ ]:
np.median(arr)

In [84]:
np.median(matriz,1)

array([ 2., 11.])

#### std()
Nos permite conocer la desviación estándar de un conjunto de datos.
Se puede calcular de forma general o por filas o por columnas.

In [85]:
np.std(arr)

5.102940328869229

In [86]:
np.std(matriz,0)

array([4. , 3.5, 4.5, 4.5, 5.5])

#### var()
Podemos tener la varianza en un conjunto de datos. Se puede calcular de forma general o por filas o por columnas.

In [87]:
np.var(arr)

26.04

In [ ]:
np.var(matriz,0)

#### mean()
Calcula la media de un conjunto de datos. Se puede calcular de forma general o por filas o por columnas.

In [89]:
np.mean(arr)

7.6

In [91]:
np.mean(matriz)

7.6

In [92]:
np.mean(matriz,0)

array([ 5. ,  5.5,  6.5,  9.5, 11.5])

#### concatener(array1,array2)
Nos permite concatenear arrays.

In [124]:
a = np.random.randint(1,10,(2,2))
b = np.random.randint(1,10,(2,2))

In [99]:
a,b

(array([[7, 4],
        [2, 8]]),
 array([[8, 4],
        [5, 1]]))

In [100]:
np.concatenate((a,b))

array([[7, 4],
       [2, 8],
       [8, 4],
       [5, 1]])

In [104]:
np.concatenate((a,b),axis=1)

array([[7, 4, 8, 4],
       [2, 8, 5, 1]])

#### expand_dim()
Nos permite expandir la dimensión de un array.

In [147]:
c = np.array([1,2])
c.ndim

1

In [139]:
c = np.expand_dims(c,axis=0)
c

array([[1, 2]])

In [131]:
c = np.expand_dims(c,axis=1)
c

array([[1],
       [2]])

In [144]:
np.concatenate((a,c),axis=0)
#np.concatenate((a,c),axis=1) #Nos genera un error porque aunque sean de la misma dimensión, no son del mismo tamaño de la matriz.

array([[6, 3],
       [7, 7],
       [1, 2]])

#### T (Transpuesta de una matriz)

In [151]:
d = np.random.randint(2,10,(2,3))
d

array([[9, 4, 6],
       [7, 7, 8]])

In [152]:
d.T

array([[9, 7],
       [4, 7],
       [6, 8]])